#!/bin/bash

set -exo pipefail

sudo dnf install -y \
    osbuild-composer composer-cli cockpit-composer \
    bash-completion podman genisoimage syslinux \
    createrepo syslinux yum-utils selinux-policy-devel jq wget lorax

sudo systemctl enable osbuild-composer.socket --now
sudo systemctl enable cockpit.socket --now
sudo firewall-cmd -q --add-service=cockpit
sudo firewall-cmd -q --add-service=cockpit --permanent
