#!/bin/bash

set -e -o pipefail

REPOROOT="$(git rev-parse --show-toplevel)"
MIRRORDIR="${REPOROOT}/builds/mirror"
BUILD_ARCH=$(uname -i)

usage() {
    local error_message="$1"

    if [ -n "$error_message" ]; then
        echo "ERROR: $error_message"
        echo
    fi

    echo "Usage: $(basename $0) <path_or_url_to_MicroShift_RPMs>"
    exit 1
}

title() {
    echo -e "\E[34m# $1\E[00m";
}

if [ $# -ne 1 ] ; then
    usage "Missing path or URL to MicroSHift RPMs."
fi
MICROSHIFT_RPM_SOURCE=$1


mkdir -p "${MIRRORDIR}"
pushd "${MIRRORDIR}" &>/dev/null

title "Downloading MicroShift RPMs"
# Copy MicroShift RPM packages
rm -rf microshift-local 2>/dev/null || true
if [[ "${MICROSHIFT_RPM_SOURCE}" == http* ]] ; then
    wget -q -nd -r -L -P microshift-local -A rpm "${MICROSHIFT_RPM_SOURCE}"
else
    cp -TR "${MICROSHIFT_RPM_SOURCE}" microshift-local
fi
# Exit if no RPM packages were found
if [ $(find microshift-local -name '*.rpm' | wc -l) -eq 0 ] ; then
    echo "No RPM packages were found at '${MICROSHIFT_RPM_SOURCE}'. Exiting..."
    exit 1
fi
title "Creating local MicroShift repo"
createrepo microshift-local >/dev/null

title "Mirror OpenShift repo"
# Download openshift local RPM packages (noarch for python and selinux packages)
rm -rf openshift-local 2>/dev/null || true
reposync -n -a ${BUILD_ARCH} -a noarch --download-path openshift-local \
            --repo=rhocp-4.11-for-rhel-8-${BUILD_ARCH}-rpms \
            --repo=fast-datapath-for-rhel-8-${BUILD_ARCH}-rpms >/dev/null

# Remove coreos packages to avoid conflicts
find openshift-local -name \*coreos\* -exec rm -f {} \;
# Exit if no RPM packages were found
if [ $(find openshift-local -name '*.rpm' | wc -l) -eq 0 ] ; then
    echo "No RPM packages were found at the 'rhocp-4.11-for-rhel-8-${BUILD_ARCH}-rpms' repository. Exiting..."
    exit 1
fi
createrepo openshift-local >/dev/null

title "Mirror Ansible repo"
# Download openshift local RPM packages (noarch for python and selinux packages)
rm -rf ansible-local 2>/dev/null || true
reposync -n -a ${BUILD_ARCH} -a noarch --download-path ansible-local \
            --repo=ansible-2.9-for-rhel-8-x86_64-rpms >/dev/null
createrepo ansible-local >/dev/null

title "Done"
popd &>/dev/null
